name: custom_lint_usage
description: A demo app using custom lint
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: 0.8.0
  custom_lints_dart:
    path: custom_lints_dart
